baseURL = "/"
languageCode = "en-us"
disablePathToLower = true
enableGitInfo = true
theme = "amethyst"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  
[params]
title = "jamfest"
description = "jamfesteq.com"
enableFooter = false
enableGitHubEdit = true
gitHubLink = "https://github.com/xackery/jamfest"
# bookSearchExclude = ?
# bookServiceWorker = ?
# bookCollapseSection = ?
# bookComments = ?
# bookCommitPath = ?
# bookDateFormat = ?
bookEditPath = true
# bookFlatSection = ?
# bookHref = ?
# bookLogo = ?
# bookMenuBundle = false
# bookRepo = ?
bookSearch = true
# bookSection = ?
# bookServiceWorker = ?
# bookTheme = ?
# bookToC = ?
# bookTranslatedOnly = ?
# class = ?
# contentDir = "/content"
enableCallouts = true
# enableCodeBlockCopy = ?
# enableCodeBlockTitle = ?
# enableContextualBacklinks = ?
enableSemanticSearch = false
enableLatex = false
enableLinkPreview = true
# enableSPA = ?
# favicon = ?
# image = ?
# links = ?
# name = ?
# search = ?
# enableToc = ?


[languages]
  [languages.en]
    disabled = false
    languageCode = ''
    languageDirection = ''
    languageName = ''
    title = ''
    weight = 0

